package se.citerus.dddsample.domain.model.cargo;

import org.apache.commons.lang3.Validate;

import java.util.Objects;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 *  
 */
public record TrackingId(String id) {

  public TrackingId {
    Objects.requireNonNull(id);
    Validate.notEmpty(id);
  }

}
