@startuml
skinparam monochrome false
skinparam defaultFontName Courier
skinparam sequenceMessageAlign center

participant "BookingServiceImpl" as bs #lightgreen
participant "CargoRepository" as cr #lightblue
participant "LocationRepository" as lr #lightblue
participant "Cargo" as c #lightpink
participant "RouteSpecification" as rs #lightpink
participant "Itinerary" as i #lightpink
participant "Delivery" as d #lightpink

[-> bs: changeDestination(trackingId, unLocode)
activate bs #lightgreen

bs -> cr: find(trackingId)
activate cr #lightblue
cr --> bs: cargo
deactivate cr

bs -> lr: find(unLocode)
activate lr #lightblue
lr --> bs: newDestination
deactivate lr

bs -> c: origin()
activate c #lightpink
c --> bs: origin
deactivate c

bs -> c: routeSpecification()
activate c #lightpink
c --> bs: specification
deactivate c

create rs
bs -> rs: new(origin, newDestination,\nspecification.arrivalDeadline())
activate rs #lightpink
rs --> bs
deactivate rs

bs -> c: specifyNewRoute(routeSpecification)
activate c #lightpink

c -> c: itinerary()
activate i #lightpink
i --> c: currentItinerary
deactivate i

c -> rs: isSatisfiedBy(currentItinerary)
activate rs #lightpink
rs --> c: satisfied
deactivate rs

c -> d: updateOnRouting(routeSpecification, itinerary)
activate d #lightpink
d --> c: delivery
deactivate d

c --> bs
deactivate c

bs -> cr: store(cargo)
activate cr #lightblue
cr --> bs
deactivate cr

[<-- bs
deactivate bs

@enduml 