@startuml
skinparam monochrome false
skinparam defaultFontName Courier
skinparam sequenceMessageAlign center

participant "HandlingEventServiceImpl" as hes #lightgreen
participant "HandlingEventFactory" as hef #lightpink
participant "HandlingEvent" as he #lightpink
participant "HandlingEventRepositoryJPA" as her #lightblue
participant "ApplicationEvents" as ae #lightgreen

[-> hes: registerHandlingEvent(completionTime,\ntrackingId, voyageNumber,\nunLocode, type)
activate hes #lightgreen

hes -> hef: createHandlingEvent(registrationTime,\ncompletionTime, trackingId,\nvoyageNumber, unLocode, type)
activate hef #lightpink
create he
hef -> he: new
activate he #lightpink

he -> he: validateLocation()
he -> he: validateVoyage()
he -> he: validateTimeConstraints()

he --> hef
deactivate he
hef --> hes: event
deactivate hef

hes -> her: store(event)
activate her #lightblue
her --> hes
deactivate her

hes -> ae: cargoWasHandled(event)
activate ae #lightgreen
ae --> hes
deactivate ae

[<-- hes
deactivate hes

@enduml 